### ISSUE TITLE
Nullable types

### ISSUE THREAD

**Issue by piotrczyz** [bcc-code/bcc-linq#15]
If you're filtering on a nullable type the the `ApplyRuleFilter` throws an exception:
`Contributions.Contracts.Standard.Exceptions.ApiRequestException : Failed to retrieve data from /contributions/Projects?limit=100&page=1. Status code: BadRequest. Content: {"error":{"code":null,"message":"Expression of type 'System.Nullable1[System.DateTime]' cannot be used for parameter of type 'System.Object' of method 'Double ToDouble(System.Object)' (Parameter 'arg0')"},"errors":[]}`

```if (!string.IsNullOrEmpty(jsonFilter))
        {
            var filter = new Filter(jsonFilter);
            basicQuery = basicQuery.ApplyRuleFilter(filter);
        }```

**Comment by leo-schick** [comment]
@piotrczyz @ketiovv  Can you test if that issue still exist with the new `ApplyApiRequest` extension method #41 ?

**Comment by leo-schick** [comment]
@piotrczyz @ketiovv This issue is stale. Please respond. Otherwise I will soon close it as not planned.
