### ISSUE TITLE
Linq support for selecting Scalar

### ISSUE THREAD

**Issue by leo-schick** [bcc-code/bcc-linq#26]
Linq queries selecting a scalar value are not possible. For example, calling

``` c#
var query = from p in api.Persons
            select p.Age;
```

is not possible, but 

``` c#
var query = from p in api.Persons
            select new { p.Age };
```

is possible.

It is easy to use the workaround given above (introducing an anonymous type in the select clause), but this restriction does not allow us to use aggregat functions like this:
``` c#
double averageAge = (
    from p in api.Persons
    select p.Age
).Average();
```

**Comment by rvanoord** [comment]
Would a solution here be to create a "wrapper" that is unwrapped after the query is executed if the "unsupported" syntax (i.e. a scalar select) is encounterd?

**Comment by leo-schick** [comment]
I am not yet sure. But this would only fix sequential calls. For asynchronous calls, we need to discuss if we should "reinvent" the wheel or rely on other libraries, see my comment here: https://github.com/bcc-code/rule-filter-parser-dotnet/issues/29#issuecomment-1582278210
