### ISSUE TITLE
Add extension function to apply IApiRequest on a IQueryable object

### ISSUE THREAD

**Issue by leo-schick** [bcc-code/bcc-linq#41]
The current [`ApplyRuleFilter`](https://github.com/bcc-code/bcc-linq/blob/main/src/BccCode.Linq/Extensions/CollectionsExtensions.cs#L11) extension method makes it possible to apply a filter on IQueryable. But there are many other options like `limit`, `offset`, `aggregte`, `sort`, `fields` which we could apply to IQueryable.

I suggest to add a new `IQueryable<TSource> ApplyApiRequest<TSource>(IApiRequest)` which applies the IApiRequest properties `Fields`, `Filter`, `Sort`, `Limit`, `Offset`, `Page`, `GroupBy`, `Deep` and `Alias` in a single extension method. The IApiRequest properties `Meta` and `Aggregate` are not implemented by this.

**Comment by leo-schick** [comment]
@piotrczyz Can you give feedback about this? I think this would make the code [here](https://github.com/bcc-code/bcc-contributions-api/blob/main/src/Contributions.Api/Services/ContributionService.cs#L38C1-L64) easier to implement.

**Comment by piotrczyz** [comment]
Sounds interesting. So you won't need to pass those as a params to a method, will you? Can you show the usage how it would look like or what the use case is?

**Comment by leo-schick** [comment]
It is especially designed to be used on server side. For example, you will get all of these parameters and now you need to pass them to a IQueryable object from entity framework.

Look at the code here up to line 59: https://github.com/bcc-code/bcc-contributions-api/blob/main/src/Contributions.Api/Services/ProjectService.cs#L32

A lot of this code is repetitive and will be used similarly for each endpoint.

The new function would do that in a single command. The new code would look similar to this:

``` csharp
var basicQuery = _repository.Query()
            .AsNoTracking();

var projects = await basicQuery
            . ApplyApiRequest(request)
            .ToListAsync(cancellationToken);
```
(The request bust be passed to the service class to make this work)

The function “ApplyApiRequest” takes care of the `filters`, `limit`, `offset` and the `sort` in a single command.

**Comment by piotrczyz** [comment]
Definitely! This is something what we're thinking as a follow up step. Good suggestion!
